#ifndef STEPPERMOTOR_CONFIG_H

#define STEPPERMOTOR_CONFIG_H

#define STEPPERMOTOR_PORT PORTC

#define STEPPERMOTOR_PIN0 PIN0

#define STEPPERMOTOR_PIN1 PIN1

#define STEPPERMOTOR_PIN2 PIN2

#define STEPPERMOTOR_PIN3 PIN3


#endif