/*
File Name:STEPPERMOTOR_program
Author:DohaOsama
Date:18/9/2021
Description:STEPPERMOTOR Driver 
version 1.0
*/

#include "../../LIB/BIT_MATH.h"

#include "../../LIB/STD_TYPES.h"

#include "../../MCAL/DIO/DIO_interface.h"

#include "STEPPERMOTOR_interface.h"

#include "STEPPERMOTOR_private.h"

#include "STEPPERMOTOR_config.h"

#include <util/delay.h>

void STEPPERMOTOR_voidInit(void)//intiation function
{
	DIO_voidSetPinDirection(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN0,OUTPUT);//Blue
	DIO_voidSetPinDirection(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN1,OUTPUT);//Pink
	DIO_voidSetPinDirection(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN2,OUTPUT);//Yellow
	DIO_voidSetPinDirection(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN3,OUTPUT);//Oranger
	DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN0,HIGH);//active coil 1
	DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN1,HIGH);
	DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN2,HIGH);
	DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN3,HIGH);
}
void STEPPERMOTOR_voidStepperFullStep(void)
{
	u16 LocalIteration;
	for(LocalIteration=STEPPER_INITIAL_ITERATION;LocalIteration<STEPPER_TOTAL_ITERATION;LocalIteration++)
	{
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN0,LOW);//active coil 1
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN1,HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN2,HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN3,HIGH);
		_delay_ms(2);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN0,HIGH);//active coil 2
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN1,LOW);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN2,HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN3,HIGH);
		_delay_ms(2);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN0,HIGH);//active coil 3
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN1,HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN2,LOW);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN3,HIGH);
		_delay_ms(2);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN0,HIGH);//active coil 4
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN1,HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN2,HIGH);
		DIO_voidSetPinValue(STEPPERMOTOR_PORT,STEPPERMOTOR_PIN3,LOW);
		_delay_ms(2);
	}
}
